### ISSUE TITLE
Road to Annix 1.0 Release

### ISSUE THREAD

**Issue by Yesterday17** [ProjectAnni/annix#7]
There're lots of missing features to implement and dozens of pending usability issues to resolve. Here's a detailed TODO list for all the problems.

Using issue instead of Project because it's more flexible to comment and trace current status.

```[tasklist]
## Missing Features
- [ ] https://github.com/ProjectAnni/annix/issues/22
- [ ] https://github.com/ProjectAnni/annix/issues/23
- [ ] https://github.com/ProjectAnni/annix/issues/24
- [x] Favorite track
- [x] Favorite album
- [ ] Favorite playlist
- [ ] Recent search
- [ ] Custom font: Custom lyric font depending on language
- [x] #8
- [x] Share current playing track information
- [ ] 2FA on login
- [ ] Register
- [ ] Upload lyric to Anniv
- [ ] Edit lyrics
- [ ] LRC maker
- [ ] LRC/Karaoke time offset
- [ ] Share tracks
- [ ] Manage share links
- [ ] anni:// scheme specification
- [x] Playback statistics: Basic implementation
- [ ] Playback statistics: Do not track short playbacks
- [ ] UI to display recent played tracks
- [ ] UI to display played times of a track
- [ ] UI to display total played times of a track across anniv server
```

```[tasklist]
## Before Release
- [ ] Changelog
```

```[tasklist]
## Usability Issues
- [x] Progress Indicator when logging in to an Anniv server
- [ ] Home page improvements
- [ ] Localization on tag types
- [ ] Showing nested tags in tag view
- [ ] Add new annil library
- [ ] Retry if download has failed
- [ ] Speed up favorite (cache favorites at local first, then wait for remote response)
- [ ] Move the light/dark mode toggle button to settings page
- [ ] Auto-refresh annil albums
- [x] Manual refresh annil albums
- [x] Refactor current playlist to a page(?)
- [x] Android notification should not blink after changing playing track
- [ ] [P3] Animations
- [x] Error handling on notification https://github.com/ProjectAnni/annix/commit/79637c94ce2d85e866aed09bd97a5f66dba08f6b
- [ ] Optimize position of the login FAB in login page
```

```[tasklist]
## CI/CD
- [x] Fix broken `Publish to Testflight` https://github.com/ProjectAnni/annix/commit/7bdeb9578c44df98e5e7a2ccac495dbdcfdb7119 https://github.com/actions/runner-images/issues/6507#issuecomment-1301636292
- [x] Fix compatibility issue after upgrading to flutter 3.13 https://github.com/ProjectAnni/annix/issues/29
- [x] Build `simple_audio` on iOS https://github.com/erikas-taroza/simple_audio/issues/30
```

```[tasklist]
## Works to be done before stable release
- [ ] Move all developer setting items to a separated page
```

```[tasklist]
## Postponed features
- [ ] Menubar app on macOS
- [ ] Auto theme color on Android 12
```
